### ISSUE TITLE
Dataset is not exactly in alphabetical order

### ISSUE THREAD

**Issue by csc-jm** [lexibank/ivanisuansu#2]
I was looking at the word list and noticed that `"the shit"` was at the very last position in the list after all the other letters like w and y. This seems like an oversight because everything else seems to be in proper alphabetical order. Can you please fix this

**Comment by LinguList** [comment]
This is not about the dataset but the *questionnaire*, which you can find [here](https://concepticon.clld.org/contributions/Sagart-2019-250), and this questionnaire, which has been published already, has this order for items, which we cannot simply change because we find it does not correspond to some alphabetical order.
